Feature/revision requests
SOBotics/SwiftStack pull request #14
Opened 2016-12-22 13:22 UTC by FelixSFD

I have added `SugestedEdit` and `Revision` including all related requests

2016-12-24 17:12 UTC, NobodyNada requested changes
Great!  Just a couple of little documentation things.  Merry Christmas!

2016-12-24 17:12 UTC, NobodyNada commented on Sources/RequestsRevisions.swift
> +     - parameter ids: The revision ID to fetch.
`ids` should be `id` here and on line 113

2016-12-24 17:12 UTC, NobodyNada commented on Sources/RequestsSuggestedEdits.swift
> +
`ids` again.  I might have gotten this wrong in RequestsQuestions.

2016-12-25 09:40 UTC, FelixSFD commented
I fixed the parts you mentioned. There are some more problems (documentation of completion handlers), but let's fix them in an other branch

2017-01-04 21:04 UTC, NobodyNada approved these changes

2017-01-04 21:04 UTC, merged