Feature/more answer requests
SOBotics/SwiftStack pull request #19
Opened 2017-01-14 18:30 UTC by FelixSFD

Added `/answers`, `/answers/{ids}` and `/answers/{ids}/questions`

2017-01-16 03:42 UTC, NobodyNada requested changes
Great!  Just a couple of little typos.

Also, when do you think we should release `1.0.0`?

2017-01-16 03:42 UTC, NobodyNada commented on Sources/RequestsAnswers.swift
> +            "answer",
Shouldn't this be `answers`?

2017-01-16 03:42 UTC, NobodyNada commented on Sources/RequestsAnswers.swift
> +//  Created by Felix Deil on 14.01.17.
Did you mean to include your full (?) name here?

2017-01-16 03:42 UTC, NobodyNada commented on Sources/RequestsAnswers.swift
> +     - author: NobodyNada
The `author` is wrong for this method and the methods below it

2017-01-19 10:44 UTC, FelixSFD commented on Sources/RequestsAnswers.swift
> +//  Created by Felix Deil on 14.01.17.
oops. Thanks :-D

2017-01-19 10:45 UTC, FelixSFD commented on Sources/RequestsAnswers.swift
> +            "answer",
yep. I'll change that

2017-01-19 16:21 UTC, NobodyNada approved these changes

2017-01-19 16:22 UTC, merged